version: '3.8'
services:
  billing:
    build: ./billing
    ports:
      - '3000:3000'
  statistics:
    build: ./statistics
    ports:
      - '3001:3001'
  errors:
    build: ./errors
    ports:
      - '4000:4000'
  mongo:
    image: mongo
    restart: always
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guardian_dev
  rabbitmq:
    container_name: rabbitmq
    ports:
      - '15673:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    image: 'rabbitmq:3-management'
