{application,torch,
             [{applications,[kernel,stdlib,elixir,logger,phoenix,phoenix_html,
                             gettext,scrivener_ecto,filtrex,timex]},
              {description,"Rapid admin generator for Phoenix"},
              {modules,['Elixir.Mix.Tasks.Torch.Gen.Html',
                        'Elixir.Mix.Tasks.Torch.Install',
                        'Elixir.Mix.Tasks.Torch.Uninstall','Elixir.Mix.Torch',
                        'Elixir.Torch','Elixir.Torch.Config',
                        'Elixir.Torch.FilterView','Elixir.Torch.FlashView',
                        'Elixir.Torch.Gettext','Elixir.Torch.Helpers',
                        'Elixir.Torch.I18n','Elixir.Torch.I18n.Backend',
                        'Elixir.Torch.PageView','Elixir.Torch.PaginationView',
                        'Elixir.Torch.TableView']},
              {registered,[]},
              {vsn,"3.5.0"}]}.
